CREATE TABLE `assets` (`id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key', `parent_id` int NOT NULL DEFAULT '0' COMMENT 'Nested set parent.', `lft` int NOT NULL DEFAULT '0' COMMENT 'Nested set lft.', `rgt` int NOT NULL DEFAULT '0' COMMENT 'Nested set rgt.', `level` int unsigned NOT NULL COMMENT 'The cached level in the nested tree.', `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The unique name for the asset.\n', `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The descriptive title for the asset.', `rules` varchar(5120) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JSON encoded access control.', PRIMARY KEY (`id`), UNIQUE KEY `idx_asset_name` (`name`), KEY `idx_lft_rgt` (`lft`,`rgt`), KEY `idx_parent_id` (`parent_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `associations` (`id` int NOT NULL COMMENT 'A reference to the associated item.', `context` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The context of the associated item.', `key` char(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The key for the association computed from an md5 on associated ids.', PRIMARY KEY (`context`,`id`), KEY `idx_key` (`key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `banner_clients` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `contact` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `extrainfo` text COLLATE utf8mb4_unicode_ci NOT NULL, `state` tinyint NOT NULL DEFAULT '0', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `metakey` text COLLATE utf8mb4_unicode_ci NOT NULL, `own_prefix` tinyint NOT NULL DEFAULT '0', `metakey_prefix` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `purchase_type` tinyint NOT NULL DEFAULT '-1', `track_clicks` tinyint NOT NULL DEFAULT '-1', `track_impressions` tinyint NOT NULL DEFAULT '-1', PRIMARY KEY (`id`), KEY `idx_own_prefix` (`own_prefix`), KEY `idx_metakey_prefix` (`metakey_prefix`(100))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `banner_tracks` (`track_date` datetime NOT NULL, `track_type` int unsigned NOT NULL, `banner_id` int unsigned NOT NULL, `count` int unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`track_date`,`track_type`,`banner_id`), KEY `idx_track_date` (`track_date`), KEY `idx_track_type` (`track_type`), KEY `idx_banner_id` (`banner_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `banners` (`id` int NOT NULL AUTO_INCREMENT, `cid` int NOT NULL DEFAULT '0', `type` int NOT NULL DEFAULT '0', `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `imptotal` int NOT NULL DEFAULT '0', `impmade` int NOT NULL DEFAULT '0', `clicks` int NOT NULL DEFAULT '0', `clickurl` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `state` tinyint NOT NULL DEFAULT '0', `catid` int unsigned NOT NULL DEFAULT '0', `description` text COLLATE utf8mb4_unicode_ci NOT NULL, `custombannercode` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL, `sticky` tinyint unsigned NOT NULL DEFAULT '0', `ordering` int NOT NULL DEFAULT '0', `metakey` text COLLATE utf8mb4_unicode_ci NOT NULL, `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `own_prefix` tinyint(1) NOT NULL DEFAULT '0', `metakey_prefix` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `purchase_type` tinyint NOT NULL DEFAULT '-1', `track_clicks` tinyint NOT NULL DEFAULT '-1', `track_impressions` tinyint NOT NULL DEFAULT '-1', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `publish_up` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `publish_down` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `reset` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `created` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `created_by` int unsigned NOT NULL DEFAULT '0', `created_by_alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `modified` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `modified_by` int unsigned NOT NULL DEFAULT '0', `version` int unsigned NOT NULL DEFAULT '1', PRIMARY KEY (`id`), KEY `idx_state` (`state`), KEY `idx_own_prefix` (`own_prefix`), KEY `idx_metakey_prefix` (`metakey_prefix`(100)), KEY `idx_banner_catid` (`catid`), KEY `idx_language` (`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `categories` (`id` int NOT NULL AUTO_INCREMENT, `asset_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the assets table.', `parent_id` int unsigned NOT NULL DEFAULT '0', `lft` int NOT NULL DEFAULT '0', `rgt` int NOT NULL DEFAULT '0', `level` int unsigned NOT NULL DEFAULT '0', `path` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `extension` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `note` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `description` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL, `published` tinyint(1) NOT NULL DEFAULT '0', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `access` int unsigned NOT NULL DEFAULT '0', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `metadesc` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'The meta description for the page.', `metakey` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'The meta keywords for the page.', `metadata` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'JSON encoded metadata properties.', `created_user_id` int unsigned NOT NULL DEFAULT '0', `created_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `modified_user_id` int unsigned NOT NULL DEFAULT '0', `modified_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `hits` int unsigned NOT NULL DEFAULT '0', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `version` int unsigned NOT NULL DEFAULT '1', PRIMARY KEY (`id`), KEY `cat_idx` (`extension`,`published`,`access`), KEY `idx_access` (`access`), KEY `idx_checkout` (`checked_out`), KEY `idx_path` (`path`(100)), KEY `idx_left_right` (`lft`,`rgt`), KEY `idx_alias` (`alias`(100)), KEY `idx_language` (`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contact_details` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `con_position` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `address` text COLLATE utf8mb4_unicode_ci, `suburb` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `state` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `country` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `postcode` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `telephone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `fax` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `misc` mediumtext COLLATE utf8mb4_unicode_ci, `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `email_to` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `default_con` tinyint unsigned NOT NULL DEFAULT '0', `published` tinyint(1) NOT NULL DEFAULT '0', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime DEFAULT NULL, `ordering` int NOT NULL DEFAULT '0', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `user_id` int NOT NULL DEFAULT '0', `catid` int NOT NULL DEFAULT '0', `access` int unsigned NOT NULL DEFAULT '0', `mobile` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `webpage` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `sortname1` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `sortname2` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `sortname3` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `language` varchar(7) COLLATE utf8mb4_unicode_ci NOT NULL, `created` datetime NOT NULL, `created_by` int unsigned NOT NULL DEFAULT '0', `created_by_alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `modified` datetime NOT NULL, `modified_by` int unsigned NOT NULL DEFAULT '0', `metakey` text COLLATE utf8mb4_unicode_ci NOT NULL, `metadesc` text COLLATE utf8mb4_unicode_ci NOT NULL, `metadata` text COLLATE utf8mb4_unicode_ci NOT NULL, `featured` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Set if contact is featured.', `xreference` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'A reference to enable linkages to external data sets.', `publish_up` datetime DEFAULT NULL, `publish_down` datetime DEFAULT NULL, `version` int unsigned NOT NULL DEFAULT '1', `hits` int unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `idx_access` (`access`), KEY `idx_checkout` (`checked_out`), KEY `idx_state` (`published`), KEY `idx_catid` (`catid`), KEY `idx_createdby` (`created_by`), KEY `idx_featured_catid` (`featured`,`catid`), KEY `idx_language` (`language`), KEY `idx_xreference` (`xreference`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `content` (`id` int unsigned NOT NULL AUTO_INCREMENT, `asset_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the assets table.', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `introtext` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL, `fulltext` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL, `state` tinyint NOT NULL DEFAULT '0', `catid` int unsigned NOT NULL DEFAULT '0', `created` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `created_by` int unsigned NOT NULL DEFAULT '0', `created_by_alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `modified` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `modified_by` int unsigned NOT NULL DEFAULT '0', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `publish_up` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `publish_down` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `images` text COLLATE utf8mb4_unicode_ci NOT NULL, `urls` text COLLATE utf8mb4_unicode_ci NOT NULL, `attribs` varchar(5120) COLLATE utf8mb4_unicode_ci NOT NULL, `version` int unsigned NOT NULL DEFAULT '1', `ordering` int NOT NULL DEFAULT '0', `metakey` text COLLATE utf8mb4_unicode_ci NOT NULL, `metadesc` text COLLATE utf8mb4_unicode_ci NOT NULL, `access` int unsigned NOT NULL DEFAULT '0', `hits` int unsigned NOT NULL DEFAULT '0', `metadata` text COLLATE utf8mb4_unicode_ci NOT NULL, `featured` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Set if article is featured.', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The language code for the article.', `xreference` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'A reference to enable linkages to external data sets.', PRIMARY KEY (`id`), KEY `idx_access` (`access`), KEY `idx_checkout` (`checked_out`), KEY `idx_state` (`state`), KEY `idx_catid` (`catid`), KEY `idx_createdby` (`created_by`), KEY `idx_featured_catid` (`featured`,`catid`), KEY `idx_language` (`language`), KEY `idx_xreference` (`xreference`), KEY `idx_alias` (`alias`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `content_frontpage` (`content_id` int NOT NULL DEFAULT '0', `ordering` int NOT NULL DEFAULT '0', PRIMARY KEY (`content_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `content_rating` (`content_id` int NOT NULL DEFAULT '0', `rating_sum` int unsigned NOT NULL DEFAULT '0', `rating_count` int unsigned NOT NULL DEFAULT '0', `lastip` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', PRIMARY KEY (`content_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `content_types` (`type_id` int unsigned NOT NULL AUTO_INCREMENT, `type_title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `type_alias` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `table` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `rules` text COLLATE utf8mb4_unicode_ci NOT NULL, `field_mappings` text COLLATE utf8mb4_unicode_ci NOT NULL, `router` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `content_history_options` varchar(5120) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'JSON string for com_contenthistory options', PRIMARY KEY (`type_id`), KEY `idx_alias` (`type_alias`(100))) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contentitem_tag_map` (`type_alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `core_content_id` int unsigned NOT NULL COMMENT 'PK from the core content table', `content_item_id` int NOT NULL COMMENT 'PK from the content type table', `tag_id` int unsigned NOT NULL COMMENT 'PK from the tag table', `tag_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Date of most recent save for this tag-item', `type_id` mediumint NOT NULL COMMENT 'PK from the content_type table', UNIQUE KEY `uc_ItemnameTagid` (`type_id`,`content_item_id`,`tag_id`), KEY `idx_tag_type` (`tag_id`,`type_id`), KEY `idx_date_id` (`tag_date`,`tag_id`), KEY `idx_core_content_id` (`core_content_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Maps items from content tables to tags';

CREATE TABLE `core_log_searches` (`search_term` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `hits` int unsigned NOT NULL DEFAULT '0') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `extensions` (`extension_id` int NOT NULL AUTO_INCREMENT, `package_id` int NOT NULL DEFAULT '0' COMMENT 'Parent package ID for extensions installed as a package.', `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL, `type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL, `element` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL, `folder` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL, `client_id` tinyint NOT NULL, `enabled` tinyint NOT NULL DEFAULT '0', `access` int unsigned NOT NULL DEFAULT '1', `protected` tinyint NOT NULL DEFAULT '0', `manifest_cache` text COLLATE utf8mb4_unicode_ci NOT NULL, `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `namespace` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `ordering` int DEFAULT '0', `state` int DEFAULT '0', `note` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`extension_id`), KEY `element_clientid` (`element`,`client_id`), KEY `element_folder_clientid` (`element`,`folder`,`client_id`), KEY `extension` (`type`,`element`,`folder`,`client_id`)) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fields` (`id` int unsigned NOT NULL AUTO_INCREMENT, `asset_id` int unsigned NOT NULL DEFAULT '0', `context` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `group_id` int unsigned NOT NULL DEFAULT '0', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `label` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `default_value` text COLLATE utf8mb4_unicode_ci NOT NULL, `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'text', `note` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `description` text COLLATE utf8mb4_unicode_ci NOT NULL, `state` tinyint(1) NOT NULL DEFAULT '0', `required` tinyint(1) NOT NULL DEFAULT '0', `checked_out` int NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `ordering` int NOT NULL DEFAULT '0', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `fieldparams` text COLLATE utf8mb4_unicode_ci NOT NULL, `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `created_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `created_user_id` int unsigned NOT NULL DEFAULT '0', `modified_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `modified_by` int unsigned NOT NULL DEFAULT '0', `access` int NOT NULL DEFAULT '1', PRIMARY KEY (`id`), KEY `idx_checkout` (`checked_out`), KEY `idx_state` (`state`), KEY `idx_created_user_id` (`created_user_id`), KEY `idx_access` (`access`), KEY `idx_context` (`context`(191)), KEY `idx_language` (`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fields_categories` (`field_id` int NOT NULL DEFAULT '0', `category_id` int NOT NULL DEFAULT '0', PRIMARY KEY (`field_id`,`category_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fields_groups` (`id` int unsigned NOT NULL AUTO_INCREMENT, `asset_id` int unsigned NOT NULL DEFAULT '0', `context` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `note` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `description` text COLLATE utf8mb4_unicode_ci NOT NULL, `state` tinyint(1) NOT NULL DEFAULT '0', `checked_out` int NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `ordering` int NOT NULL DEFAULT '0', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `created` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `created_by` int unsigned NOT NULL DEFAULT '0', `modified` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `modified_by` int unsigned NOT NULL DEFAULT '0', `access` int NOT NULL DEFAULT '1', PRIMARY KEY (`id`), KEY `idx_checkout` (`checked_out`), KEY `idx_state` (`state`), KEY `idx_created_by` (`created_by`), KEY `idx_access` (`access`), KEY `idx_context` (`context`(191)), KEY `idx_language` (`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fields_values` (`field_id` int unsigned NOT NULL, `item_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Allow references to items which have strings as ids, eg. none db systems.', `value` text COLLATE utf8mb4_unicode_ci NOT NULL, KEY `idx_field_id` (`field_id`), KEY `idx_item_id` (`item_id`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_filters` (`filter_id` int unsigned NOT NULL AUTO_INCREMENT, `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `state` tinyint(1) NOT NULL DEFAULT '1', `created` datetime NOT NULL, `created_by` int unsigned NOT NULL DEFAULT '0', `created_by_alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `modified` datetime NOT NULL, `modified_by` int unsigned NOT NULL DEFAULT '0', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime DEFAULT NULL, `map_count` int unsigned NOT NULL DEFAULT '0', `data` text COLLATE utf8mb4_unicode_ci NOT NULL, `params` mediumtext COLLATE utf8mb4_unicode_ci, PRIMARY KEY (`filter_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_links` (`link_id` int unsigned NOT NULL AUTO_INCREMENT, `url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `route` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `title` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `description` text COLLATE utf8mb4_unicode_ci, `indexdate` datetime NOT NULL, `md5sum` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `published` tinyint(1) NOT NULL DEFAULT '1', `state` int NOT NULL DEFAULT '1', `access` int NOT NULL DEFAULT '0', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `publish_start_date` datetime DEFAULT NULL, `publish_end_date` datetime DEFAULT NULL, `start_date` datetime DEFAULT NULL, `end_date` datetime DEFAULT NULL, `list_price` double unsigned NOT NULL DEFAULT '0', `sale_price` double unsigned NOT NULL DEFAULT '0', `type_id` int NOT NULL, `object` mediumblob NOT NULL, PRIMARY KEY (`link_id`), KEY `idx_type` (`type_id`), KEY `idx_title` (`title`(100)), KEY `idx_md5` (`md5sum`), KEY `idx_url` (`url`(75)), KEY `idx_published_list` (`published`,`state`,`access`,`publish_start_date`,`publish_end_date`,`list_price`), KEY `idx_published_sale` (`published`,`state`,`access`,`publish_start_date`,`publish_end_date`,`sale_price`), KEY `idx_language` (`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_links_terms` (`link_id` int unsigned NOT NULL, `term_id` int unsigned NOT NULL, `weight` float unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`link_id`,`term_id`), KEY `idx_term_weight` (`term_id`,`weight`), KEY `idx_link_term_weight` (`link_id`,`term_id`,`weight`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_logging` (`searchterm` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `md5sum` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `query` blob NOT NULL, `hits` int NOT NULL DEFAULT '1', `results` int NOT NULL DEFAULT '0', PRIMARY KEY (`md5sum`), KEY `searchterm` (`searchterm`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_taxonomy` (`id` int unsigned NOT NULL AUTO_INCREMENT, `parent_id` int unsigned NOT NULL DEFAULT '0', `lft` int NOT NULL DEFAULT '0', `rgt` int NOT NULL DEFAULT '0', `level` int unsigned NOT NULL DEFAULT '0', `path` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `alias` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `state` tinyint unsigned NOT NULL DEFAULT '1', `access` tinyint unsigned NOT NULL DEFAULT '1', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', PRIMARY KEY (`id`), KEY `idx_state` (`state`), KEY `idx_access` (`access`), KEY `idx_path` (`path`(100)), KEY `idx_left_right` (`lft`,`rgt`), KEY `idx_alias` (`alias`(100)), KEY `idx_language` (`language`), KEY `idx_parent_published` (`parent_id`,`state`,`access`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_taxonomy_map` (`link_id` int unsigned NOT NULL, `node_id` int unsigned NOT NULL, PRIMARY KEY (`link_id`,`node_id`), KEY `link_id` (`link_id`), KEY `node_id` (`node_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_terms` (`term_id` int unsigned NOT NULL AUTO_INCREMENT, `term` varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `stem` varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `common` tinyint unsigned NOT NULL DEFAULT '0', `phrase` tinyint unsigned NOT NULL DEFAULT '0', `weight` float unsigned NOT NULL DEFAULT '0', `soundex` varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `links` int NOT NULL DEFAULT '0', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', PRIMARY KEY (`term_id`), UNIQUE KEY `idx_term_language` (`term`,`language`), KEY `idx_term_phrase` (`term`,`phrase`), KEY `idx_stem_phrase` (`stem`,`phrase`), KEY `idx_soundex_phrase` (`soundex`,`phrase`), KEY `idx_stem` (`stem`), KEY `idx_language` (`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_terms_common` (`term` varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `custom` int NOT NULL DEFAULT '0', UNIQUE KEY `idx_term_language` (`term`,`language`), KEY `idx_lang` (`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_tokens` (`term` varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `stem` varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `common` tinyint unsigned NOT NULL DEFAULT '0', `phrase` tinyint unsigned NOT NULL DEFAULT '0', `weight` float unsigned NOT NULL DEFAULT '1', `context` tinyint unsigned NOT NULL DEFAULT '2', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', KEY `idx_word` (`term`), KEY `idx_context` (`context`), KEY `idx_stem` (`stem`), KEY `idx_language` (`language`)) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_tokens_aggregate` (`term_id` int unsigned NOT NULL, `term` varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `stem` varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `common` tinyint unsigned NOT NULL DEFAULT '0', `phrase` tinyint unsigned NOT NULL DEFAULT '0', `term_weight` float unsigned NOT NULL DEFAULT '0', `context` tinyint unsigned NOT NULL DEFAULT '2', `context_weight` float unsigned NOT NULL DEFAULT '0', `total_weight` float unsigned NOT NULL DEFAULT '0', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', KEY `token` (`term`), KEY `keyword_id` (`term_id`)) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `finder_types` (`id` int unsigned NOT NULL AUTO_INCREMENT, `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL, `mime` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', PRIMARY KEY (`id`), UNIQUE KEY `title` (`title`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `languages` (`lang_id` int unsigned NOT NULL AUTO_INCREMENT, `asset_id` int unsigned NOT NULL DEFAULT '0', `lang_code` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `title` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `title_native` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `sef` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `image` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `description` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL, `metakey` text COLLATE utf8mb4_unicode_ci NOT NULL, `metadesc` text COLLATE utf8mb4_unicode_ci NOT NULL, `sitename` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `published` int NOT NULL DEFAULT '0', `access` int unsigned NOT NULL DEFAULT '0', `ordering` int NOT NULL DEFAULT '0', PRIMARY KEY (`lang_id`), UNIQUE KEY `idx_sef` (`sef`), UNIQUE KEY `idx_langcode` (`lang_code`), KEY `idx_access` (`access`), KEY `idx_ordering` (`ordering`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mail_templates` (`template_id` varchar(127) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `subject` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `body` text COLLATE utf8mb4_unicode_ci NOT NULL, `htmlbody` text COLLATE utf8mb4_unicode_ci NOT NULL, `attachments` text COLLATE utf8mb4_unicode_ci NOT NULL, `params` text COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`template_id`,`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `menu` (`id` int NOT NULL AUTO_INCREMENT, `menutype` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The type of menu this item belongs to. FK to menu_types.menutype', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The display title of the menu item.', `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'The SEF alias of the menu item.', `note` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `path` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The computed path of the menu item based on the alias field.', `link` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The actually link the menu item refers to.', `type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The type of link: Component, URL, Alias, Separator', `published` tinyint NOT NULL DEFAULT '0' COMMENT 'The published state of the menu link.', `parent_id` int unsigned NOT NULL DEFAULT '1' COMMENT 'The parent menu item in the menu tree.', `level` int unsigned NOT NULL DEFAULT '0' COMMENT 'The relative level in the tree.', `component_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'FK to extensions.id', `checked_out` int unsigned NOT NULL DEFAULT '0' COMMENT 'FK to users.id', `checked_out_time` datetime DEFAULT NULL, `browserNav` tinyint NOT NULL DEFAULT '0' COMMENT 'The click behaviour of the link.', `access` int unsigned NOT NULL DEFAULT '0' COMMENT 'The access level required to view the menu item.', `img` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The image of the menu item.', `template_style_id` int unsigned NOT NULL DEFAULT '0', `params` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JSON encoded data for the menu item.', `lft` int NOT NULL DEFAULT '0' COMMENT 'Nested set lft.', `rgt` int NOT NULL DEFAULT '0' COMMENT 'Nested set rgt.', `home` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Indicates if this menu item is the home or default page.', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `client_id` tinyint NOT NULL DEFAULT '0', `publish_up` datetime DEFAULT NULL, `publish_down` datetime DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `idx_client_id_parent_id_alias_language` (`client_id`,`parent_id`,`alias`(100),`language`), KEY `idx_componentid` (`component_id`,`menutype`,`published`,`access`), KEY `idx_menutype` (`menutype`), KEY `idx_left_right` (`lft`,`rgt`), KEY `idx_alias` (`alias`(100)), KEY `idx_path` (`path`(100)), KEY `idx_language` (`language`)) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `menu_types` (`id` int unsigned NOT NULL AUTO_INCREMENT, `asset_id` int unsigned NOT NULL DEFAULT '0', `menutype` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL, `title` varchar(48) COLLATE utf8mb4_unicode_ci NOT NULL, `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `client_id` int NOT NULL DEFAULT '0', PRIMARY KEY (`id`), UNIQUE KEY `idx_menutype` (`menutype`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `messages` (`message_id` int unsigned NOT NULL AUTO_INCREMENT, `user_id_from` int unsigned NOT NULL DEFAULT '0', `user_id_to` int unsigned NOT NULL DEFAULT '0', `folder_id` tinyint unsigned NOT NULL DEFAULT '0', `date_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `state` tinyint(1) NOT NULL DEFAULT '0', `priority` tinyint unsigned NOT NULL DEFAULT '0', `subject` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `message` text COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`message_id`), KEY `useridto_state` (`user_id_to`,`state`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `messages_cfg` (`user_id` int unsigned NOT NULL DEFAULT '0', `cfg_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `cfg_value` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', UNIQUE KEY `idx_user_var_name` (`user_id`,`cfg_name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `modules` (`id` int NOT NULL AUTO_INCREMENT, `asset_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the assets table.', `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `note` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `content` text COLLATE utf8mb4_unicode_ci, `ordering` int NOT NULL DEFAULT '0', `position` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime DEFAULT NULL, `publish_up` datetime DEFAULT NULL, `publish_down` datetime DEFAULT NULL, `published` tinyint(1) NOT NULL DEFAULT '0', `module` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `access` int unsigned NOT NULL DEFAULT '0', `showtitle` tinyint unsigned NOT NULL DEFAULT '1', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `client_id` tinyint NOT NULL DEFAULT '0', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`id`), KEY `published` (`published`,`access`), KEY `newsfeeds` (`module`,`published`), KEY `idx_language` (`language`)) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `modules_menu` (`moduleid` int NOT NULL DEFAULT '0', `menuid` int NOT NULL DEFAULT '0', PRIMARY KEY (`moduleid`,`menuid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `newsfeeds` (`catid` int NOT NULL DEFAULT '0', `id` int unsigned NOT NULL AUTO_INCREMENT, `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `link` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `published` tinyint(1) NOT NULL DEFAULT '0', `numarticles` int unsigned NOT NULL DEFAULT '1', `cache_time` int unsigned NOT NULL DEFAULT '3600', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `ordering` int NOT NULL DEFAULT '0', `rtl` tinyint NOT NULL DEFAULT '0', `access` int unsigned NOT NULL DEFAULT '0', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `created` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `created_by` int unsigned NOT NULL DEFAULT '0', `created_by_alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `modified` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `modified_by` int unsigned NOT NULL DEFAULT '0', `metakey` text COLLATE utf8mb4_unicode_ci NOT NULL, `metadesc` text COLLATE utf8mb4_unicode_ci NOT NULL, `metadata` text COLLATE utf8mb4_unicode_ci NOT NULL, `xreference` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'A reference to enable linkages to external data sets.', `publish_up` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `publish_down` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `description` text COLLATE utf8mb4_unicode_ci NOT NULL, `version` int unsigned NOT NULL DEFAULT '1', `hits` int unsigned NOT NULL DEFAULT '0', `images` text COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`id`), KEY `idx_access` (`access`), KEY `idx_checkout` (`checked_out`), KEY `idx_state` (`published`), KEY `idx_catid` (`catid`), KEY `idx_createdby` (`created_by`), KEY `idx_language` (`language`), KEY `idx_xreference` (`xreference`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `overrider` (`id` int NOT NULL AUTO_INCREMENT COMMENT 'Primary Key', `constant` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `string` text COLLATE utf8mb4_unicode_ci NOT NULL, `file` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `postinstall_messages` (`postinstall_message_id` bigint unsigned NOT NULL AUTO_INCREMENT, `extension_id` bigint NOT NULL DEFAULT '700' COMMENT 'FK to extensions', `title_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Lang key for the title', `description_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Lang key for description', `action_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `language_extension` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'com_postinstall' COMMENT 'Extension holding lang keys', `language_client_id` tinyint NOT NULL DEFAULT '1', `type` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'link' COMMENT 'Message type - message, link, action', `action_file` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'RAD URI to the PHP file containing action method', `action` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Action method name or URL', `condition_file` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'RAD URI to file holding display condition method', `condition_method` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Display condition method, must return boolean', `version_introduced` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '3.2.0' COMMENT 'Version when this message was introduced', `enabled` tinyint NOT NULL DEFAULT '1', PRIMARY KEY (`postinstall_message_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `redirect_links` (`id` int unsigned NOT NULL AUTO_INCREMENT, `old_url` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL, `new_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `referer` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL, `comment` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `hits` int unsigned NOT NULL DEFAULT '0', `published` tinyint NOT NULL, `created_date` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `modified_date` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `header` smallint NOT NULL DEFAULT '301', PRIMARY KEY (`id`), KEY `idx_old_url` (`old_url`(100)), KEY `idx_link_modifed` (`modified_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `schemas` (`extension_id` int NOT NULL, `version_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`extension_id`,`version_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `session` (`session_id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `client_id` tinyint unsigned DEFAULT NULL, `guest` tinyint unsigned DEFAULT '1', `time` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT '', `data` mediumtext COLLATE utf8mb4_unicode_ci, `userid` int DEFAULT '0', `username` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT '', PRIMARY KEY (`session_id`), KEY `userid` (`userid`), KEY `time` (`time`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tags` (`id` int unsigned NOT NULL AUTO_INCREMENT, `parent_id` int unsigned NOT NULL DEFAULT '0', `lft` int NOT NULL DEFAULT '0', `rgt` int NOT NULL DEFAULT '0', `level` int unsigned NOT NULL DEFAULT '0', `path` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `note` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `description` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL, `published` tinyint(1) NOT NULL DEFAULT '0', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `access` int unsigned NOT NULL DEFAULT '0', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `metadesc` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The meta description for the page.', `metakey` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The meta keywords for the page.', `metadata` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JSON encoded metadata properties.', `created_user_id` int unsigned NOT NULL DEFAULT '0', `created_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `created_by_alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `modified_user_id` int unsigned NOT NULL DEFAULT '0', `modified_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `images` text COLLATE utf8mb4_unicode_ci NOT NULL, `urls` text COLLATE utf8mb4_unicode_ci NOT NULL, `hits` int unsigned NOT NULL DEFAULT '0', `language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL, `version` int unsigned NOT NULL DEFAULT '1', `publish_up` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `publish_down` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', PRIMARY KEY (`id`), KEY `tag_idx` (`published`,`access`), KEY `idx_access` (`access`), KEY `idx_checkout` (`checked_out`), KEY `idx_path` (`path`(100)), KEY `idx_left_right` (`lft`,`rgt`), KEY `idx_alias` (`alias`(100)), KEY `idx_language` (`language`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `template_overrides` (`id` int unsigned NOT NULL AUTO_INCREMENT, `template` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `hash_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `extension_id` int DEFAULT '0', `state` tinyint NOT NULL DEFAULT '0', `action` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `client_id` tinyint unsigned NOT NULL DEFAULT '0', `created_date` datetime NOT NULL, `modified_date` datetime DEFAULT NULL, PRIMARY KEY (`id`), KEY `idx_template` (`template`), KEY `idx_extension_id` (`extension_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `template_styles` (`id` int unsigned NOT NULL AUTO_INCREMENT, `template` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `client_id` tinyint unsigned NOT NULL DEFAULT '0', `home` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`id`), KEY `idx_template` (`template`), KEY `idx_home` (`home`)) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ucm_base` (`ucm_id` int unsigned NOT NULL, `ucm_item_id` int NOT NULL, `ucm_type_id` int NOT NULL, `ucm_language_id` int NOT NULL, PRIMARY KEY (`ucm_id`), KEY `idx_ucm_item_id` (`ucm_item_id`), KEY `idx_ucm_type_id` (`ucm_type_id`), KEY `idx_ucm_language_id` (`ucm_language_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ucm_content` (`core_content_id` int unsigned NOT NULL AUTO_INCREMENT, `core_type_alias` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'FK to the content types table', `core_title` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `core_alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `core_body` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL, `core_state` tinyint(1) NOT NULL DEFAULT '0', `core_checked_out_time` datetime DEFAULT NULL, `core_checked_out_user_id` int unsigned NOT NULL DEFAULT '0', `core_access` int unsigned NOT NULL DEFAULT '0', `core_params` text COLLATE utf8mb4_unicode_ci NOT NULL, `core_featured` tinyint unsigned NOT NULL DEFAULT '0', `core_metadata` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'JSON encoded metadata properties.', `core_created_user_id` int unsigned NOT NULL DEFAULT '0', `core_created_by_alias` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `core_created_time` datetime NOT NULL, `core_modified_user_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'Most recent user that modified', `core_modified_time` datetime NOT NULL, `core_language` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `core_publish_up` datetime DEFAULT NULL, `core_publish_down` datetime DEFAULT NULL, `core_content_item_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'ID from the individual type table', `asset_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the assets table.', `core_images` text COLLATE utf8mb4_unicode_ci NOT NULL, `core_urls` text COLLATE utf8mb4_unicode_ci NOT NULL, `core_hits` int unsigned NOT NULL DEFAULT '0', `core_version` int unsigned NOT NULL DEFAULT '1', `core_ordering` int NOT NULL DEFAULT '0', `core_metakey` text COLLATE utf8mb4_unicode_ci NOT NULL, `core_metadesc` text COLLATE utf8mb4_unicode_ci NOT NULL, `core_catid` int unsigned NOT NULL DEFAULT '0', `core_xreference` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'A reference to enable linkages to external data sets.', `core_type_id` int unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`core_content_id`), KEY `tag_idx` (`core_state`,`core_access`), KEY `idx_access` (`core_access`), KEY `idx_alias` (`core_alias`(100)), KEY `idx_language` (`core_language`), KEY `idx_title` (`core_title`(100)), KEY `idx_modified_time` (`core_modified_time`), KEY `idx_created_time` (`core_created_time`), KEY `idx_content_type` (`core_type_alias`(100)), KEY `idx_core_modified_user_id` (`core_modified_user_id`), KEY `idx_core_checked_out_user_id` (`core_checked_out_user_id`), KEY `idx_core_created_user_id` (`core_created_user_id`), KEY `idx_core_type_id` (`core_type_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Contains core content data in name spaced fields';

CREATE TABLE `ucm_history` (`version_id` int unsigned NOT NULL AUTO_INCREMENT, `ucm_item_id` int unsigned NOT NULL, `ucm_type_id` int unsigned NOT NULL, `version_note` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Optional version name', `save_date` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `editor_user_id` int unsigned NOT NULL DEFAULT '0', `character_count` int unsigned NOT NULL DEFAULT '0' COMMENT 'Number of characters in this version.', `sha1_hash` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'SHA1 hash of the version_data column.', `version_data` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'json-encoded string of version data', `keep_forever` tinyint NOT NULL DEFAULT '0' COMMENT '0=auto delete, 1=keep', PRIMARY KEY (`version_id`), KEY `idx_ucm_item_id` (`ucm_type_id`,`ucm_item_id`), KEY `idx_save_date` (`save_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `update_sites` (`update_site_id` int NOT NULL AUTO_INCREMENT, `name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '', `type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '', `location` text COLLATE utf8mb4_unicode_ci NOT NULL, `enabled` int DEFAULT '0', `last_check_timestamp` bigint DEFAULT '0', `extra_query` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT '', PRIMARY KEY (`update_site_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Update Sites';

CREATE TABLE `update_sites_extensions` (`update_site_id` int NOT NULL DEFAULT '0', `extension_id` int NOT NULL DEFAULT '0', PRIMARY KEY (`update_site_id`,`extension_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Links extensions to update sites';

CREATE TABLE `updates` (`update_id` int NOT NULL AUTO_INCREMENT, `update_site_id` int DEFAULT '0', `extension_id` int DEFAULT '0', `name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '', `description` text COLLATE utf8mb4_unicode_ci NOT NULL, `element` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '', `type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '', `folder` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '', `client_id` tinyint DEFAULT '0', `version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '', `data` text COLLATE utf8mb4_unicode_ci NOT NULL, `detailsurl` text COLLATE utf8mb4_unicode_ci NOT NULL, `infourl` text COLLATE utf8mb4_unicode_ci NOT NULL, `extra_query` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT '', PRIMARY KEY (`update_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Available Updates';

CREATE TABLE `user_keys` (`id` int unsigned NOT NULL AUTO_INCREMENT, `user_id` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL, `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `series` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL, `time` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL, `uastring` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `series` (`series`), KEY `user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_notes` (`id` int unsigned NOT NULL AUTO_INCREMENT, `user_id` int unsigned NOT NULL DEFAULT '0', `catid` int unsigned NOT NULL DEFAULT '0', `subject` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `body` text COLLATE utf8mb4_unicode_ci NOT NULL, `state` tinyint NOT NULL DEFAULT '0', `checked_out` int unsigned NOT NULL DEFAULT '0', `checked_out_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `created_user_id` int unsigned NOT NULL DEFAULT '0', `created_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `modified_user_id` int unsigned NOT NULL DEFAULT '0', `modified_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `review_time` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `publish_up` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `publish_down` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', PRIMARY KEY (`id`), KEY `idx_user_id` (`user_id`), KEY `idx_category_id` (`catid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_profiles` (`user_id` int NOT NULL, `profile_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL, `profile_value` text COLLATE utf8mb4_unicode_ci NOT NULL, `ordering` int NOT NULL DEFAULT '0', UNIQUE KEY `idx_user_id_profile_key` (`user_id`,`profile_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Simple user profile storage table';

CREATE TABLE `user_usergroup_map` (`user_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'Foreign Key to users.id', `group_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'Foreign Key to usergroups.id', PRIMARY KEY (`user_id`,`group_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `usergroups` (`id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key', `parent_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'Adjacency List Reference Id', `lft` int NOT NULL DEFAULT '0' COMMENT 'Nested set lft.', `rgt` int NOT NULL DEFAULT '0' COMMENT 'Nested set rgt.', `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', PRIMARY KEY (`id`), UNIQUE KEY `idx_usergroup_parent_title_lookup` (`parent_id`,`title`), KEY `idx_usergroup_title_lookup` (`title`), KEY `idx_usergroup_adjacency_lookup` (`parent_id`), KEY `idx_usergroup_nested_set_lookup` (`lft`,`rgt`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `users` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `username` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `password` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `block` tinyint NOT NULL DEFAULT '0', `sendEmail` tinyint DEFAULT '0', `registerDate` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `lastvisitDate` datetime NOT NULL DEFAULT '2023-01-01 00:00:00', `activation` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `params` text COLLATE utf8mb4_unicode_ci NOT NULL, `lastResetTime` datetime NOT NULL DEFAULT '2023-01-01 00:00:00' COMMENT 'Date of last password reset', `resetCount` int NOT NULL DEFAULT '0' COMMENT 'Count of password resets since lastResetTime', `otpKey` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Two factor authentication encrypted keys', `otep` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'One time emergency passwords', `requireReset` tinyint NOT NULL DEFAULT '0' COMMENT 'Require user to reset password on next login', PRIMARY KEY (`id`), KEY `idx_name` (`name`(100)), KEY `idx_block` (`block`), KEY `username` (`username`), KEY `email` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `utf8_conversion` (`converted` tinyint NOT NULL DEFAULT '0') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `viewlevels` (`id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key', `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', `ordering` int NOT NULL DEFAULT '0', `rules` varchar(5120) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JSON encoded access control.', PRIMARY KEY (`id`), UNIQUE KEY `idx_assetgroup_title_lookup` (`title`)) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `workflow_associations` (`item_id` int NOT NULL DEFAULT '0' COMMENT 'Extension table id value', `stage_id` int NOT NULL COMMENT 'Foreign Key to workflow_stages.id', `extension` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`item_id`,`extension`), KEY `idx_item_stage_extension` (`item_id`,`stage_id`,`extension`), KEY `idx_item_id` (`item_id`), KEY `idx_stage_id` (`stage_id`), KEY `idx_extension` (`extension`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `workflow_stages` (`id` int NOT NULL AUTO_INCREMENT, `asset_id` int DEFAULT '0', `ordering` int NOT NULL DEFAULT '0', `workflow_id` int NOT NULL, `published` tinyint NOT NULL DEFAULT '0', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `description` text COLLATE utf8mb4_unicode_ci NOT NULL, `default` tinyint NOT NULL DEFAULT '0', `checked_out_time` datetime DEFAULT NULL, `checked_out` int NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `idx_workflow_id` (`workflow_id`), KEY `idx_checked_out` (`checked_out`), KEY `idx_title` (`title`(191)), KEY `idx_asset_id` (`asset_id`), KEY `idx_default` (`default`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `workflow_transitions` (`id` int NOT NULL AUTO_INCREMENT, `asset_id` int DEFAULT '0', `ordering` int NOT NULL DEFAULT '0', `workflow_id` int NOT NULL, `published` tinyint NOT NULL DEFAULT '0', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `description` text COLLATE utf8mb4_unicode_ci NOT NULL, `from_stage_id` int NOT NULL, `to_stage_id` int NOT NULL, `options` text COLLATE utf8mb4_unicode_ci NOT NULL, `checked_out_time` datetime DEFAULT NULL, `checked_out` int NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `idx_title` (`title`(191)), KEY `idx_asset_id` (`asset_id`), KEY `idx_checked_out` (`checked_out`), KEY `idx_from_stage_id` (`from_stage_id`), KEY `idx_to_stage_id` (`to_stage_id`), KEY `idx_workflow_id` (`workflow_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `workflows` (`id` int NOT NULL AUTO_INCREMENT, `asset_id` int DEFAULT '0', `published` tinyint NOT NULL DEFAULT '0', `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `description` text COLLATE utf8mb4_unicode_ci NOT NULL, `extension` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `default` tinyint NOT NULL DEFAULT '0', `ordering` int NOT NULL DEFAULT '0', `created` datetime NOT NULL, `created_by` int NOT NULL DEFAULT '0', `modified` datetime NOT NULL, `modified_by` int NOT NULL DEFAULT '0', `checked_out_time` datetime DEFAULT NULL, `checked_out` int NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `idx_asset_id` (`asset_id`), KEY `idx_title` (`title`(191)), KEY `idx_extension` (`extension`), KEY `idx_default` (`default`), KEY `idx_created` (`created`), KEY `idx_created_by` (`created_by`), KEY `idx_modified` (`modified`), KEY `idx_modified_by` (`modified_by`), KEY `idx_checked_out` (`checked_out`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

